#!/bin/bash

echo "Enter Number: "
read n
f=0
for ((i = 2 ; i<=n/2 ; i++))
do
if ((n%i == 0))
then
f=1
fi
done
if (($f == 0))
then
echo "Prime Number"
else
echo "Not prime"
echo "Prime factors:"
fi
for((i = 2; i<=n/2; i++))
do
if ((n%i == 0))
then
echo $i

fi done
