#!/bin/bash

echo "How many numbers?"
read n
number=1
for((i=1; i<=$n; i++))
do
  for((j=1; j<=$n - i; j++))
  do
    echo -n "  "
  done
  for((j=1; j<=i; j++))
  do
    echo -n "$number   "
    ((number=number+1))
  done
  echo
done
